name: Docker Build & Release

on:
  push:
    branches:
      - main
    paths:
      - "versions.json"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read Versions
        run: |
          echo "DNSPROXY_VERSION=$(jq -r '.dnsproxy' versions.json)" >> $GITHUB_ENV
          echo "PIHOLE_VERSION=$(jq -r '.pihole' versions.json)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build.sh as executable
        run: chmod +x build.sh

      - name: Build & Push Docker Image
        run: ./build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "dnsproxy-${{ env.DNSPROXY_VERSION }}-pihole-${{ env.PIHOLE_VERSION }}"
          name: "Release dnsproxy-${{ env.DNSPROXY_VERSION }} & pihole-${{ env.PIHOLE_VERSION }}"
          body: "### Changes:\n- dnsproxy: v${{ env.DNSPROXY_VERSION }}\n- pihole: v${{ env.PIHOLE_VERSION }}"
